### ISSUE TITLE
408 Error when pulling Socket-Proxy

### ISSUE THREAD

**Issue by AnonymeusOfficial** [htpcBeginner/auto-traefik#1]
1. This script has only been confirmed to work on Ubuntu\Debian variants.

################# Version Check #############

[32m[INFO][0m You are running latest version of the script: 1.1.2.

[32m--->What does this script do?:[0m

1. It automates most of the steps needed in setting up Docker, Socket Proxy, and Traefik with Let's Encrypt SSL certificates. It also sets up basic HTTP authentication.
2. You will have to provide your domainname, Linux uername, HTTP Auth username, HTTP Auth password, Cloudflare Email, Cloudflare Global API Key, and your host environment.
3. It does most of the checks needed, including if ports 80 and 443 are free, port forwarding is setup, if DNS records in Cloudflare resolve properly, etc.
4. It creates all necessary files and folders with appropriate permissions, including those that are needed for Traefik configuration.
5. It setups Socket Proxy first. If successful, proceeds to setup Traefik with Staging SSL certificates. Finally, if staging is successful, then Traefik with real Let's Encrypt SSL certificates is setup.

Paid supporters of this script may get free support on the exclusive Auto-Traefik channel on our Discord: [34mhttps://www.smarthomebeginner.com/go/discord-atd/[0m.

[32m--->Please read and agree to the following disclaimers:[0m

1. This script has only been confirmed to work on Ubuntu\Debian variants.
2. [34mwww.smarthomebeginner.com[0m, its authors, or script contributors cannot be held accountable for any problems that might occur while using this script, including when modified and reproduced by others.
3. If you did not run this script with sudo, you maybe asked for your root password during installation.
4. While it may work in other environments, this script has been tested only on a fresh install of OS.
5. This script does not delete any contents and no information is collected and sent outside of your local environement.
6. By proceeding you agree to assume all risks and authorize the script to install any required packages and/or make any necessary changes.

################# Prerequisites #############

[32mPREREQUISITES:[0m

Ensure that you have done the following before proceeding:

[34mReference:[0m https://www.smarthomebeginner.com/docker-media-server-2022/#5_Proper_DNS_Records
1. DNS A record on Cloudflare DNS pointing to your WAN IP.
2. DNS CNAME record on Cloudflare DNS pointing to your root domain name.
3. Both DNS records do not have proxy enabled (should be gray-clouded for initial setup).

[34mReference:[0m https://www.smarthomebeginner.com/docker-media-server-2022/#6_Cloudflare_SSL_Settings
4. Cloudflare SSL settings set to 'Full' mode.

[34mReference:[0m https://www.smarthomebeginner.com/setup-port-forwarding-on-router/
5. Ports 80 and 443 forwarded from your internet router/gateway to your server's internal IP address.

################# Required Information #############

[32mINFORMATION REQUIRED TO PROCEED:[0m

Previously supplied information found:

Domain Name = anony-serer.dev
Linux Username = anonymeus
Basic HTTP Authentication Username = admin
Basic HTTP Authentication Password = ******** (Not shown here for security. Check /tmp/auto-traefik/auto_traefik_constants)
Cloudflare Account Email = ******** (Not shown here for security. Check /tmp/auto-traefik/auto_traefik_constants)
Cloudflare Global API Key = ******** (Not shown here for security. Check /tmp/auto-traefik/auto_traefik_constants)
Unprivileged LXC Environment? y

################# Running Preliminary Checks #############

[32mRUNNING PRELIMINARY CHECKS:[0m

Checking Linux username...

Checking WAN IP...
[INFO] Current IP: [PUBLIC IP]

Checking domain resolution...
[INFO] anony-serer.dev resolves to: [PUBLIC IP]
[INFO] anony-serer.dev resolves to this server.

Checking subdomain resolution...
[INFO] www.anony-serer.dev resolves to:[PUBLIC IP]
[INFO] Subdomain resolves to this server. Wildcard (*) CNAME record set properly.

Checking Cloudflare proxy status for DNS A record...
[INFO] Cloudflare proxy is disabled/gray-clouded.
[INFO] DNS A record is good.

Checking Cloudflare proxy status for DNS CNAME record...
[INFO] Cloudflare proxy is disabled/gray-clouded.
[INFO] DNS CNAME record is good.

################# System and Docker Checks #############

Performing System and Docker checks...
[INFO] Docker already installed. Checking for updates. You maybe asked for your Linux user password.
[INFO] Checking for updates.
[INFO] Docker is running. Stopping all containers...

[INFO] Installing some required packages.

################# Checking if Ports are Exposed #############

Checking if port 80 is exposed to the internet...
[INFO] Port 80 is open to the internet and nothing is listening on it!

Checking if port 443 is exposed to the internet...
[INFO] Port 443 is open to the internet and nothing is listening on it!

[32m[INFO][0m All checks passed sucessfully. Time to roll.

################# Creating Files and Folders #############

Creating Docker environement...
[31m[WARNING][0m /home/anonymeus/docker already exists. Moving it to /home/anonymeus/docker_20231019_223221
[INFO] Docker Root Folder (to store all container data) created: /home/anonymeus/docker

Setting ACLs for Docker Root Folder
[INFO] ACLs set for /home/anonymeus/docker

Creating few more folders...
[INFO] appdata folder created: /home/anonymeus/docker/appdata
[INFO] shared folder folder created: /home/anonymeus/docker/shared

################# Creating .htpasswd File for Basic HTTP Authentication #############

Creating .htpasswd file using username and password previously supplied.
[INFO] .htpasswd set to root ownership and 600 permisssions.

Creating .env file to store environmental variables for containers.
[INFO] Added PUID: 1000
[INFO] Added PGID: 1000

Ensuring timezone information is available...
[INFO] TZ set to: America/New_York

Setting few more environmental variables...
[INFO] USERDIR set to: /home/anonymeus
[INFO] DOCKERDIR set to: /home/anonymeus/docker
[INFO] Added trusted local IPs to LOCAL_IPS
[INFO] Added Cloudflare IPs to CLOUDFLARE_IPS.
[INFO] DOMAINNAME set to: anony-serer.dev
[INFO] HOSTNAME set to: anonyserver-main

[INFO] Here are the contents of the .env file:

PUID=1000
PGID=1000
TZ=America/New_York
USERDIR=/home/anonymeus
DOCKERDIR=/home/anonymeus/docker
LOCAL_IPS=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
CLOUDFLARE_IPS=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
DOMAINNAME=anony-serer.dev
HOSTNAME=anonyserver-main

################# Creating .htpasswd File for Basic HTTP Authentication #############

Creating docker-compose-t2.yml file...
[INFO] Created network blocks.
[INFO] Added compose for Docker Socket Proxy.

[INFO] Unprivileged LXC. So disabling privileged mode.

Starting the stack (previously running containers may be stopped/removed)...

Waiting for Socket Proxy to start...
[31m[ERROR][0m Timed out. Could not verify if socket-proxy is running.
For troubleshooting/support, output of this script was saved here: /tmp/auto-traefik/auto-traefik_20231019_223057.log

**Comment by AnonymeusOfficial** [comment]
I still am having issues, any help is greatly appreciated.

**Comment by SimpleHomelab** [comment]
Please use out Discord Server for support. There is a separate channel for auto-traefik support. You can just link to this issue page.
